#!/usr/bin/env bash
set -euo pipefail

CONFIG_DIR="/config"
CONFIG_FILE="$CONFIG_DIR/configuration.yml"
USERS_FILE="$CONFIG_DIR/users_database.yml"

echo "==> Authelia Railway entrypoint starting..."

# ---------------------------------------------------------------------------
# 1. DEFAULTS — every env var gets a sensible fallback
# ---------------------------------------------------------------------------

# Core
export AUTHELIA_DOMAIN="${AUTHELIA_DOMAIN:-example.com}"
export AUTHELIA_AUTH_URL="${AUTHELIA_AUTH_URL:-https://auth.${AUTHELIA_DOMAIN}}"
export AUTHELIA_LOG_LEVEL="${AUTHELIA_LOG_LEVEL:-info}"
export AUTHELIA_DEFAULT_2FA_METHOD="${AUTHELIA_DEFAULT_2FA_METHOD:-totp}"

# Secrets — Railway should inject these via ${{secret(32)}}
export AUTHELIA_SESSION_SECRET="${AUTHELIA_SESSION_SECRET:?ERROR: AUTHELIA_SESSION_SECRET is required}"
export AUTHELIA_STORAGE_ENCRYPTION_KEY="${AUTHELIA_STORAGE_ENCRYPTION_KEY:?ERROR: AUTHELIA_STORAGE_ENCRYPTION_KEY is required}"
export AUTHELIA_JWT_SECRET="${AUTHELIA_JWT_SECRET:?ERROR: AUTHELIA_JWT_SECRET is required}"

# Session
export SESSION_NAME="${SESSION_NAME:-authelia_session}"
export SESSION_EXPIRATION="${SESSION_EXPIRATION:-1h}"
export SESSION_INACTIVITY="${SESSION_INACTIVITY:-5m}"
export SESSION_REMEMBER_ME="${SESSION_REMEMBER_ME:-1M}"

# Access control default policy
export ACCESS_CONTROL_DEFAULT_POLICY="${ACCESS_CONTROL_DEFAULT_POLICY:-two_factor}"

# Storage — PostgreSQL
export AUTHELIA_STORAGE_POSTGRES_HOST="${AUTHELIA_STORAGE_POSTGRES_HOST:?ERROR: AUTHELIA_STORAGE_POSTGRES_HOST is required}"
export AUTHELIA_STORAGE_POSTGRES_PORT="${AUTHELIA_STORAGE_POSTGRES_PORT:-5432}"
export AUTHELIA_STORAGE_POSTGRES_DATABASE="${AUTHELIA_STORAGE_POSTGRES_DATABASE:-authelia}"
export AUTHELIA_STORAGE_POSTGRES_USERNAME="${AUTHELIA_STORAGE_POSTGRES_USERNAME:?ERROR: AUTHELIA_STORAGE_POSTGRES_USERNAME is required}"
export AUTHELIA_STORAGE_POSTGRES_PASSWORD="${AUTHELIA_STORAGE_POSTGRES_PASSWORD:?ERROR: AUTHELIA_STORAGE_POSTGRES_PASSWORD is required}"

# Redis
export AUTHELIA_SESSION_REDIS_HOST="${AUTHELIA_SESSION_REDIS_HOST:?ERROR: AUTHELIA_SESSION_REDIS_HOST is required}"
export AUTHELIA_SESSION_REDIS_PORT="${AUTHELIA_SESSION_REDIS_PORT:-6379}"
export AUTHELIA_SESSION_REDIS_PASSWORD="${AUTHELIA_SESSION_REDIS_PASSWORD:-}"

# ---------------------------------------------------------------------------
# 2. GENERATE configuration.yml from template
# ---------------------------------------------------------------------------

echo "==> Generating $CONFIG_FILE..."
mkdir -p "$CONFIG_DIR"

# Decide notifier block
if [[ -n "${SMTP_HOST:-}" ]]; then
  export NOTIFIER_BLOCK="notifier:
  smtp:
    address: smtp://${SMTP_HOST}:${SMTP_PORT:-587}
    username: ${SMTP_USERNAME:-}
    password: ${SMTP_PASSWORD:-}
    sender: \"${SMTP_SENDER:-Authelia <authelia@${AUTHELIA_DOMAIN}>}\"
    subject: \"[Authelia] {title}\"
    startup_check_address: ${SMTP_USERNAME:-test@authelia.com}"
else
  export NOTIFIER_BLOCK="notifier:
  disable_startup_check: true
  filesystem:
    filename: /config/notifications.txt"
fi

# Decide OIDC block
if [[ -n "${OIDC_CLIENT_ID:-}" && -n "${OIDC_CLIENT_SECRET:-}" ]]; then
  export OIDC_BLOCK="identity_providers:
  oidc:
    hmac_secret: \${AUTHELIA_OIDC_HMAC_SECRET}
    jwks:
      - key_id: default
        algorithm: RS256
        use: sig
        key: |
          \${OIDC_PRIVATE_KEY_INLINE}
    clients:
      - client_id: ${OIDC_CLIENT_ID}
        client_name: ${OIDC_CLIENT_NAME:-My App}
        client_secret: ${OIDC_CLIENT_SECRET}
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - ${OIDC_REDIRECT_URI:?ERROR: OIDC_REDIRECT_URI is required when OIDC is enabled}
        scopes:
          - openid
          - profile
          - email
          - groups
        response_types:
          - code
        grant_types:
          - authorization_code
        access_token_signed_response_alg: RS256
        userinfo_signed_response_alg: none"

  # Generate OIDC RSA key if not already present
  OIDC_KEY_FILE="$CONFIG_DIR/oidc_private.pem"
  if [[ ! -f "$OIDC_KEY_FILE" ]]; then
    echo "==> Generating OIDC RSA private key..."
    openssl genrsa -out "$OIDC_KEY_FILE" 4096 2>/dev/null
    chmod 600 "$OIDC_KEY_FILE"
  fi
  # Inline the key with proper YAML indentation
  export OIDC_PRIVATE_KEY_INLINE
  OIDC_PRIVATE_KEY_INLINE=$(sed 's/^/          /' "$OIDC_KEY_FILE")
  export AUTHELIA_OIDC_HMAC_SECRET="${AUTHELIA_OIDC_HMAC_SECRET:?ERROR: AUTHELIA_OIDC_HMAC_SECRET is required when OIDC is enabled}"
else
  export OIDC_BLOCK="# OIDC disabled. Set OIDC_CLIENT_ID and OIDC_CLIENT_SECRET to enable."
fi

# Write configuration.yml
cat > "$CONFIG_FILE" <<EOF
# Auto-generated by entrypoint.sh — do not edit manually.
# Modify environment variables and redeploy to change settings.

theme: auto

log:
  level: ${AUTHELIA_LOG_LEVEL}

server:
  address: tcp://0.0.0.0:9091/

telemetry:
  metrics:
    enabled: false

identity_validation:
  reset_password:
    jwt_secret: ${AUTHELIA_JWT_SECRET}

authentication_backend:
  password_reset:
    disable: false
  file:
    path: /config/users_database.yml
    watch: true
    password:
      algorithm: argon2id
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

session:
  secret: ${AUTHELIA_SESSION_SECRET}
  cookies:
    - name: ${SESSION_NAME}
      domain: ${AUTHELIA_DOMAIN}
      authelia_url: ${AUTHELIA_AUTH_URL}
      expiration: ${SESSION_EXPIRATION}
      inactivity: ${SESSION_INACTIVITY}
      remember_me: ${SESSION_REMEMBER_ME}
  redis:
    host: ${AUTHELIA_SESSION_REDIS_HOST}
    port: ${AUTHELIA_SESSION_REDIS_PORT}
    password: ${AUTHELIA_SESSION_REDIS_PASSWORD}

storage:
  encryption_key: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
  postgres:
    address: tcp://${AUTHELIA_STORAGE_POSTGRES_HOST}:${AUTHELIA_STORAGE_POSTGRES_PORT}
    database: ${AUTHELIA_STORAGE_POSTGRES_DATABASE}
    username: ${AUTHELIA_STORAGE_POSTGRES_USERNAME}
    password: ${AUTHELIA_STORAGE_POSTGRES_PASSWORD}
    tls:
      skip_verify: true

regulation:
  max_retries: ${REGULATION_MAX_RETRIES:-3}
  find_time: ${REGULATION_FIND_TIME:-2m}
  ban_time: ${REGULATION_BAN_TIME:-5m}

password_policy:
  standard:
    enabled: false
  zxcvbn:
    enabled: true
    min_score: 3

access_control:
  default_policy: ${ACCESS_CONTROL_DEFAULT_POLICY}
  rules:
    # Always bypass Authelia's own endpoints
    - domain: $(echo "$AUTHELIA_AUTH_URL" | sed 's|https://||')
      policy: bypass
    # Add your custom rules via ACCESS_CONTROL_RULES_EXTRA env var or by editing this file
    ${ACCESS_CONTROL_RULES_EXTRA:-}

${NOTIFIER_BLOCK}

${OIDC_BLOCK}
EOF

echo "==> configuration.yml written."

# ---------------------------------------------------------------------------
# 3. GENERATE users_database.yml (only if it doesn't already exist)
# ---------------------------------------------------------------------------

if [[ ! -f "$USERS_FILE" ]]; then
  echo "==> Generating $USERS_FILE..."

  INIT_USERNAME="${AUTHELIA_INIT_USERNAME:-admin}"
  INIT_EMAIL="${AUTHELIA_INIT_EMAIL:-admin@${AUTHELIA_DOMAIN}}"
  INIT_DISPLAY_NAME="${AUTHELIA_INIT_DISPLAY_NAME:-Administrator}"

  if [[ -z "${AUTHELIA_INIT_PASSWORD:-}" ]]; then
    echo "ERROR: AUTHELIA_INIT_PASSWORD is required on first boot to create the initial user."
    exit 1
  fi

  echo "==> Hashing initial user password (this takes a few seconds)..."
  HASHED_PASSWORD=$(authelia crypto hash generate argon2 --password "${AUTHELIA_INIT_PASSWORD}" 2>/dev/null | grep -oE '\$argon2[^[:space:]]*')

  cat > "$USERS_FILE" <<EOF
# Auto-generated by entrypoint.sh on first boot.
# Add more users by editing this file directly on the volume,
# or via Authelia's user management API.

users:
  ${INIT_USERNAME}:
    disabled: false
    displayname: "${INIT_DISPLAY_NAME}"
    password: "${HASHED_PASSWORD}"
    email: ${INIT_EMAIL}
    groups:
      - admins
      - users
EOF

  echo "==> users_database.yml written for user: $INIT_USERNAME"
  echo "==> IMPORTANT: AUTHELIA_INIT_PASSWORD was used to seed the user. You can now remove it from Railway variables."
else
  echo "==> users_database.yml already exists — skipping user generation."
fi

# ---------------------------------------------------------------------------
# 4. HAND OFF to Authelia
# ---------------------------------------------------------------------------

echo "==> Starting Authelia..."
exec authelia --config "$CONFIG_FILE"
